name: Allure Report Generation

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Generate Allure report
        uses: marketplace/actions/allure-report@v0.1.0
        with:
          results-dir: allure-results
          report-dir: allure-report
